# CactusTools 配置文件
# 用于解决服务器卡顿导致的仙人掌生长后方块状态更新异常问题

# 是否启用调试日志输出
debug-logging: false

# 延迟检查时间（单位：tick，1秒=20tick）
# 建议值：1-3，过高可能导致检查失效，过低可能影响性能
check-delay-ticks: 1

# 是否在控制台输出碰撞检测信息
log-collision-detection: true

# 插件版本信息（请勿修改）
config-version: 1.0
